# Installs cloud.ps1 and cloud-0.sh & cloud-1.sh to test VM scripts installation

name: Install Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Linux scripts
  setup-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Setup fractal user
      run: |
        sudo useradd fractal || echo "fractal user already exists"
        echo 'fractal:password1234567.' | sudo chpasswd && echo "Set password"
        sudo mkhomedir_helper fractal

        echo $HOME

    - name: Runs cloud-0.sh
      run: ./cloud-0.sh
      working-directory: linux
      env:
          LOCAL: yes
          FRACTAL_GITHUB_ACTION: yes
          
    - name: Runs cloud-1.sh
      run: ./cloud-1.sh
      working-directory: linux
      env:
          LOCAL: yes
          FRACTAL_GITHUB_ACTION: yes

  # Windows scripts
  setup-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - name: Create Fractal user
      run: |
        $pass = (ConvertTo-SecureString "password1234567." -AsPlainText -Force)
        New-LocalUser -FullName "Fractal" -Name "Fractal" -Password $pass -Description "Fractal Account"
        Add-LocalGroupMember -Group "Administrators" -Member "Fractal"
        $credentials = New-Object System.Management.Automation.PSCredential "Fractal", $pass
        Start-Process powershell.exe -Credential $credentials

    - name: Runs cloud.ps1
      run: ./cloud.ps1
      working-directory: windows
      env:
          LOCAL: yes
          NO_UPDATE: yes
          QUIET: yes
