name: Install Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Setup fractal user
      run: |
        sudo useradd Fractal \
        && echo 'Fractal:password1234567' | sudo chpasswd 
    
    - name: Install tree
      run: |
        sudo apt-get install tree
        tree
        tree /home
        env

    - name: Runs cloud-0.sh
      run: ./cloud-0.sh
      working-directory: linux
      env:
          DEBIAN_FRONTEND: "noninteractive"
          LOCAL: yes
    
    - name: Runs cloud-1.sh
      run: ./cloud-1.sh
      working-directory: linux
      env:
          DEBIAN_FRONTEND: "noninteractive"
          LOCAL: yes

  setup-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Create Fractal user
      run: |
        $pass = (ConvertTo-SecureString "password1234567." -AsPlainText -Force)
        New-LocalUser -FullName "Fractal" -Name "Fractal" -Password $pass -Description "Fractal Account"


    - name: Runs cloud.ps1
      run: ./cloud.ps1
      working-directory: windows
      env:
          LOCAL: yes

