# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Runs cloud-0.sh
      run: ./linux/cloud-0.sh
    
    - name: Runs cloud-1.sh
      run: ./linux/cloud-1.sh

